const DOMAIN="http://localhost:8080/api"

const ADD_TASK="ADD_TASK"
const REMOVE_TASK="REMOVE_TASK"
const UPDATE_TASK="UPDATE_TASK"
const ADD_COMBINE="ADD_COMBINE"

export {DOMAIN,ADD_TASK,REMOVE_TASK,UPDATE_TASK,ADD_COMBINE}