const DOMAIN="http://localhost:8080/api"

const ADD_TASK="ADD_TASK"
const REMOVE_TASK="REMOVE_TASK"
const EDIT_TASK="EDIT_TASK"
const REPLACE_ALL_TASK="REPLACE_ALL_TASK"
const UPDATE_MEMBERS="UPDATE_MEMBERS"

export {DOMAIN,ADD_TASK,REMOVE_TASK,EDIT_TASK,REPLACE_ALL_TASK,UPDATE_MEMBERS}