const DOMAIN="http://localhost:8080/api"

const ADD_TASK="ADD_TASK"
const REMOVE_TASK="REMOVE_TASK"
const UPDATE_TASK="UPDATE_TASK"
const REPLACE_ALL_TASK="REPLACE_ALL_TASK"

export {DOMAIN,ADD_TASK,REMOVE_TASK,UPDATE_TASK,REPLACE_ALL_TASK}